# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 046872f6a59dd1a42e69319c3021be251d6ce1fc23c2042ce91fdf159666d246d59e1e758dd2c3b22cec7b116d6f24ae9882fc3c0494f5e122ab5c9ce02faf11

test:
  secret_key_base: 7631e177662f09390cc4883c89e61a564f65579ac114f1844aba277e21d35b7dd8dbf87b323b41100c8e8fe640a7f305bee0b8bb3c62efc22bed9a545660f456

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
